
name: Get Secret
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
jobs:
  run_job_with_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::800380167058:role/sweii-30-role
          aws-region: us-east-2
      - name: Get Secret Value
        run: |
          echo "::add-mask::$(aws secretsmanager get-secret-value --secret-id sweii-2026-1-30/secrets --query SecretString --output text)"
